#ifndef __LOOPBACKPROG_H
#define __LOOPBACKPROG_H

#define NUM_ARGS 
#define ARG_CLIENT_SERVER 1
#define ARG_NUM_THREADS 2
#define ARG_MSG_SIZE 3

#define LOOPBACK_IP "127.0.0.1"
#define LOOPBACK_PORT 10110

#endif /* __LOOPBACKPROG_H */
